# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0006_remove_workoutset_rep_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='intensity',
            field=models.FloatField(),
        ),
    ]
