# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0008_auto_20170629_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date']},
        ),
    ]
