# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0009_auto_20170629_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='load',
            field=models.IntegerField(default='', help_text='Weight in pounds'),
        ),
    ]
