# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0011_auto_20170630_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardioset',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
